### ISSUE TITLE
Make schedule for playing sponsors ads (video) and banners on the stage

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#103]
## Goal
- Session lead knows the schedule upfront to play particular sponsors ads and banners.
- Everything should be played in 5 mins break

## TODO

- [ ] Collect all ads and videos at one place

- [ ] Sayan to submit schedules for ads by Saturday i.e. 26th Sept, 2020

- [ ] Do a dry run for the same
