### ISSUE TITLE
Diversity and pyladies tracks

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#114]
# TODO

- [ ] Get the list of sessions happening on conference days

- [ ] Prepare the schedule on hopin.to

- [ ] Get training on how to run the session by Sat 10:00 PM
