### ISSUE TITLE
Announce First Keynote Speaker 

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#70]
## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the first keynote speaker.  @aavrug 

### Pre 5PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Naomi Ceder

Image: https://www.naomiceder.tech/galleries/NaomiCeder_headshot_web.jpg
Bio
https://www.naomiceder.tech/pages/speaking/speakerbio/
Twitter: https://twitter.com/naomiceder

**Comment by iamaravindsekar** [comment]
Hello folks, done with the design for the speaker announcement... please find the file in the drive link below, Feel free to let me know if anything else is needed, Thank you!

[https://drive.google.com/drive/folders/1Fn_cNfcsbquHVARt19yCMeGY932XPaI7?usp=sharing](https://drive.google.com/drive/folders/1Fn_cNfcsbquHVARt19yCMeGY932XPaI7?usp=sharing)

**Comment by Pradhvan** [comment]
Social Media announcement
---
```
It's our pleasure to announce Naomi Ceder @NaomiCeder as the first speaker in the keynote lineup of #PyConIndia2020

Naomi is the immediate past chair of the board of directors @thePSF and the co-founder of @trans_code. 

<blog link>

<poster>

```

**Comment by sayanchowdhury** [comment]
All the action items are done. Closing the issue.
