### ISSUE TITLE
Announce Second Keynote Speaker 

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#71]
## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the second keynote speaker.  @aavrug 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Alolita Sharma
Picture URL to be used in the blog: https://in.pycon.org/2020/assets/images/alolitasharma.jpg
Bio
Alolita Sharma is a software engineer and open source advocate best known for her work on language technology. While at the Wikimedia Foundation, she expanded access to Wikipedia across hundreds of languages. Currently, she sits on the board of the Unicode Consortium (the standards setting organization that defines how software should support all of the world’s written languages) and chairs the Indic language task force of the W3C Internationalization working group which sets the standards for how languages are supported on the World Wide Web. Previously, Sharma co-founded LinuxAsia (India’s first open source business conference) and served on the boards of several advocacy organizations including the Open Source Initiative (OSI) and the Software Freedom Law Center (SFLC) - India.

Picture for website and poster: https://d2908q01vomqb2.cloudfront.net/ca3512f4dfa95a03169c5a670a4c91a19b3077b4/2018/02/23/alolitas.png

**Comment by Sc0rpi0n101** [comment]
Is there a twitter or some other handle we can also add? @sayanchowdhury

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/316

**Comment by sayanchowdhury** [comment]
@Sc0rpi0n101 https://twitter.com/alolita

**Comment by sayanchowdhury** [comment]
```
Alolita Sharma is a Principal Technologist at Amazon Web Services. She leads open source strategy and engineering for projects 
focused on observability and search including OpenTelmetry, Prometheus, Grafana, Apache Lucene and Open Distro for 
Elasticsearch. Two decades of doing open source continue to inspire her. Alolita has built and led engineering teams at Wikipedia, 
Twitter, PayPal and IBM. Alolita is passionate about language technologies that enable everyone to participate in the Web's 
information revolution. She serves on the board of Unicode Consortium and is an invited expert on W3C and ECMA workgroups. 
She has served on the boards of the Open Source Initiative (OSI) and SFLC.in. You can find her on Twitter @alolita.
```

**Comment by iamaravindsekar** [comment]
Please find the design file for Alolita Sharma in the drive folder by following the link below 

[https://drive.google.com/drive/folders/1Fn_cNfcsbquHVARt19yCMeGY932XPaI7?usp=sharing](url)

**Comment by Pradhvan** [comment]
https://drive.google.com/drive/folders/1s2NTfT4_NdtX6_ZFX_KvGUXZa3vQLwIC?usp=sharing 

Updated Keynote Poster LInk @sayanchowdhury

**Comment by Pradhvan** [comment]
Social Media Post 
---

```
It's our pleasure to announce Alolita Sharma(@alolita) as the second speaker in the keynote lineup of #PyConIndia2020

Alolita is a Principal Technologist at @awscloud and currently serves on the board of @unicode.

<Blog link>

<poster>

```

**Comment by sayanchowdhury** [comment]
Thanks everyone. Closing the issue.
