### ISSUE TITLE
Announce the Third Keynote Speaker

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#75]
## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the third keynote speaker.  @aavrug 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
James Powell

Picture URL to be used in the blog: https://in.pycon.org/2020/assets/images/jamespowell.jpg
Bio:
```
James Powell is a professional Python programmer and enthusiast. He
started working with Python in the finance industry building reporting
and analysis systems for prop trading front offices. He currently
works as a consultant building data engineering and scientific
computing platforms for a wide-range of clients using cutting-edge
open source tools like Python and React. He also offers a variety of
corporate training courses and coaching sessions in all areas of
Python.

In his spare time, he serves on the board of NumFOCUS as co-Chairman
and Vice President. NumFOCUS is the 501(c)(3) non-profit that supports
all the major tools in the Python data analysis ecosystem (incl.
pandas, numpy, jupyter, matplotlib, and others.) At NumFOCUS, he helps
build global open source communities for data scientists, data
engineers, and business analysis. He helps NumFOCUS run the PyData
conference series and has sat on speaker selection and organizing
committees for over two dozen conferences. James is also a prolific
speaker: since 2013, he has given over seventy conference talks at
over fifty Python events worldwide.
```
I will update the image later

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/317

**Comment by Pradhvan** [comment]
Social Media Post
---

It's our pleasure to announce James Powell(@dontusethiscode) as the third speaker in the keynote lineup of #PyConIndia2020.

James serves on the board of @NumFOCUS as co-Chairman and Vice President.

https://in.pycon.org/blog/2020/keynote-announcement-james-powell.html

Tickets at bit.ly/GetPyConIndiaTickets 

---

@sayanchowdhury kept a similar format as the last one.

**Comment by Pradhvan** [comment]
Poster link: https://drive.google.com/drive/folders/18_4caDmPQ_nHTAz9G0ymKNcXCPbV2kQJ?usp=sharing

**Comment by sayanchowdhury** [comment]
Thanks everyone for the help. Closing this issue.
