### ISSUE TITLE
Announce our Fourth Keynote Speaker

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#76]
## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the fourth keynote speaker.  @aavrug 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
This will go out on September 10th 2020.

**Comment by sayanchowdhury** [comment]
Name: S Anand
SubTitle: Gramener

```
Anand is a co-founder of Gramener, a data science company. He is recognized as one of India's top 10 data scientists. He leads a team that automates insights from data and narrates these as visual data stories.
```
Picture https://raw.githubusercontent.com/pythonindia/inpycon2020/3fb0806142b499fc93a56d1e96abf4d0faf530e3/assets/images/sanand.jpg

**Comment by Pradhvan** [comment]
Social Media Post 
---
It's our pleasure to announce S Anand(@sanand0) as the fourth speaker in the keynote lineup of #PyConIndia2020.

Anand is the co-founder of @Gramener and is recognized as one of India's top 10 data scientists.

https://in.pycon.org/blog/2020/keynote-announcement-s-anand.html

Tickets at bit.ly/GetPyConIndiaTickets

**Comment by iamaravindsekar** [comment]
Fourth Keynote speaker poster is here... Please find the file in this drive url... Thank You! :)

[https://drive.google.com/drive/folders/1azkohZ4VLCHko7yhh-K2JmLmkua7Bc-u?usp=sharing](url)

**Comment by sayanchowdhury** [comment]
Thanks everyone for the help. Closing this issue.
