### ISSUE TITLE
Announce Fifth Keynote Speaker

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#77]
Scheduled for 11 September 2020

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the fifth keynote speaker.  @aavrug 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Name: Victor Stinner
brief: Red Hat, CPython Core Developer
picture: https://github.com/pythonindia/inpycon2020/blob/753f583d287b46cbf204c21c56ff0dbe62068edd/assets/images/victorstinner.jpg
```
Victor Stinner is a Python core developer for 9 years. He is paid by
Red Hat to maintain Python upstream (python.org) and downstream (RHEL,
Fedora). Author of pyperf, faulthandler and tracemalloc modules, he is
working on Python performance (https://speed.python.org/), security
(http://python-security.readthedocs.io/ website) and stability (member
of the Night's Watch, maintain Python CIs: Travis CI, AppVeyor, and
the large fleet of buildbot workers). He is also mentoring Python
contributors.
```

**Comment by iamaravindsekar** [comment]
Please find the keynote speaker announcement media in the Gdrive folder url below... Thank You
[https://drive.google.com/drive/folders/1PS5BkQp1XDaU21wr5uC-QSeYS8ZEIMyB?usp=sharing](url)

**Comment by Pradhvan** [comment]
Social Media Post 
---

It's our pleasure to announce Victor Stinner(@VictorStinner) as the fifth speaker in the keynote lineup of #PyConIndia2020.

Victor is a CPython Core Developer. Over the years he has mentored numerous Python contributors

https://in.pycon.org/blog/2020/keynote-announcement-victor-stinner.html

Tickets: bit.ly/GetPyConIndiaTickets

**Comment by sayanchowdhury** [comment]
Thanks all for the help.
