### ISSUE TITLE
Announce Deepsource as Silver Sponsor

### ISSUE THREAD

**Issue by Pradhvan** [pythonindia/inpycon2020-tasks#82]
Scheduled for 18 September 2020

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display DeepSource logo  @palnabarun 

### Pre 4PM
- [x] Push a low-resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by inovizz** [comment]
> 1. The official logo that we could use on the website: https://github.com/deepsourcelabs/brand-assets/
> 2. the website that the redirect should be made for- https://deepsource.io/
> 3. A small writeup (not more than 200 words) which we could publish on the site: DeepSource continuously analyzes source code changes to find and fix issues categorized as security, performance, anti-patterns and bug-risks. It integrates with GitHub/GitLab/Bitbucket and runs analysis on every commit and pull request, discovers and fixes potential issues before they make it to production. With support for Python, Go, Ruby and JavaScript and guaranteed less than 5% false positives in results, DeepSource is trusted by open-source teams at NASA, Slack, Intel, DGraph among many others to ship good code. Free to use for open-source projects and small teams.

**Comment by inovizz** [comment]
https://github.com/deepsourcelabs/brand-assets/blob/master/wordmark.svg

Use this one on a lighter background.

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/325

**Comment by Pradhvan** [comment]
Poster: https://drive.google.com/drive/folders/1jUGobwXF20gR9vxL1Dgyx1ZPkwvKevKL?usp=sharing

**Comment by Pradhvan** [comment]
Social Media Post
___

We are delighted to announce DeepSource(@DeepSourceHQ) as Silver Sponsor for PyCon India 2020. 

Read more about @DeepSourceHQ in our blog 

https://in.pycon.org/blog/2020/sponsor-announcement-deepsource.html

#PyConIndia2020 

poster here


cc: @sayanchowdhury @inovizz

**Comment by Pradhvan** [comment]
Twitter Post: https://twitter.com/pyconindia/status/1306918439047499777

LinkedIn Post: https://www.linkedin.com/feed/update/urn:li:activity:6712685537297264640

FB Post: https://www.facebook.com/133849919970392/posts/3614574321897917/

**Comment by Pradhvan** [comment]
Thank you everyone for helping in closing the issue. 😄
