### ISSUE TITLE
Announce Auth0 as Gold Sponsors

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#83]
September 21, 5pm.

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display logo  @palnabarun 

### Pre 4PM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan

**Comment by inovizz** [comment]
Logo -   https://brandfolder.com/s/cnnzss7cq7b4xfk98sgfpmw
Website - https://a0.to/pycon-india-devs

**Comment by iamaravindsekar** [comment]
The poster for social media announcement can be found in this url,
[https://drive.google.com/file/d/1cfCzM9OUGcn7XPScGd_GKFwA0nIzNo3E/view?usp=sharing](url)

**Comment by Sc0rpi0n101** [comment]
@inovizz Can you send the sponsor text for the blog?

**Comment by inovizz** [comment]
Writeup - Auth0 provides a platform to authenticate, authorize, and secure access for applications, devices, and users. Safeguarding more than 4.5 billion login transactions each month, Auth0 secures identities so innovators can innovate, and empowers global enterprises to deliver trusted, superior digital experiences to their customers around the world.

**Comment by Pradhvan** [comment]
Social Media Posts
---

We are excited to announce Auth0(@auth0) as Gold Sponsor for PyCon India 2020. 

Read more about Auth0 in our blog.

https://in.pycon.org/blog/2020/sponsor-announcement-auth0.html

#PyConIndia2020 

Poster Here

**Comment by Pradhvan** [comment]
Announcement Posts
---

Facebook: https://www.facebook.com/133849919970392/posts/3624026597619356/

LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6713772082502647808

Twitter: https://twitter.com/pyconindia/status/1308004978993147904

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue.
