### ISSUE TITLE
Announce JetBrains as Silver Sponsor

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#85]
30th Sep - 5:00 pm

## Tasks
- [ ] Social Media announcement @Pradhvan 
- [ ] Blog post announcement @vipulgupta2048 
- [ ] Website update to display logo  @palnabarun 

### Pre 4 PM
- [ ] Push a low-resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [ ] Draft the social media announcement @Pradhvan 
- [ ] Merge the website changes @palnabarun 

### Post 5 PM
- [ ] Deploy the blog and the website @palnabarun 
- [ ] Send the social media announcements out @Pradhvan

**Comment by inovizz** [comment]
Link - https://www.jetbrains.com/

Write up - JetBrains is a global software vendor that creates professional software development tools and advanced collaboration solutions trusted by 8 million users. Since 2000, JetBrains has built a catalog of 28 products, including IntelliJ IDEA, ReSharper, PhpStorm, PyCharm, WebStorm, Rider, YouTrack, Kotlin, and Space, a new integrated team environment.

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/93641290-a6ee8f80-fa19-11ea-853b-2c8d6bf4b162.png)

**Comment by inovizz** [comment]
Let's have the PRs ready for this?

**Comment by vipulgupta2048** [comment]
Taking up the blog now

**Comment by iamaravindsekar** [comment]
The announcement poster can be found in this drive link, Thank you :) 
[https://drive.google.com/file/d/1d28XMmgUwg73hl5kJzDsF-cNn-lb-Dl7/view?usp=sharing](url)
