### ISSUE TITLE
Announcing D.E. Shaw India as Platinum Sponsor

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#86]
Scheduled for 25th Sep 5:00 PM

## Tasks
- [ ] Social Media announcement @Pradhvan 
- [ ] Blog post announcement @vipulgupta2048 
- [ ] Website update to display DeepSource logo  @palnabarun 

### Pre 4 PM
- [ ] Push a low-resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [ ] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [ ] Merge the website changes @palnabarun 
- [ ] Deploy the blog and the website @palnabarun 

### At 5 PM

- [ ] Send the social media announcements out @Pradhvan

**Comment by Sc0rpi0n101** [comment]
@inovizz Is this one also delayed, or are we doing this on time?
If yes, please send the content before night, so that I can make a PR tonight.

**Comment by inovizz** [comment]
yes, the scheduled is taken for a toss now 😉 

I'll send the updated schedule and add details in the issues.

**Comment by inovizz** [comment]
Website URL - https://www.deshawindia.com/

Website writeup - ``` D. E. Shaw India Private Limited ("D. E. Shaw India") is a part of the D. E. Shaw group, a global investment and technology development firm founded in 1988 with more than $50 billion in investment capital as of June 1, 2020, and offices in North America, Europe, and Asia. Additional information regarding D. E. Shaw India is available at www.deshawindia.com ```

Logo - 
![image](https://user-images.githubusercontent.com/3849885/94239993-3cb17f80-ff30-11ea-8838-4f1a26d65577.png)

Blog -  ```Established in 1996 as a technological development center, D. E. Shaw India has
become an integral part of the D. E. Shaw group, expanding its business into a
broad range of software and financial activities.
The firm brings together some of the sharpest minds to work on end-to-end
solutions with their global counterparts. They not only build cutting-edge
proprietary software systems that form an intrinsic part of the D. E. Shaw group’s
investment activities but also provide research and operations support to the
group’s systematic, discretionary, and hybrid strategies.
Technology is at the core of our business. Our talented and innovative engineers
engage in informed problem-solving to process large data sets into useful
analytics and forecasts using a combination of technology and deep domain
knowledge. They also work on financial data-feed infrastructure, high-
performance middleware, interactive trading systems, portfolio management and
workflow tools, and quantitative analysis.
At D. E. Shaw India, we value our people and their extraordinary work. We go to
great lengths to invest in those who think beyond the status quo, thrive in a
collaborative culture, and set the highest standards for themselves. We believe
that our diverse and inclusive work culture drives creativity, productivity, and
performance.
Our goal is to cultivate an environment of continuous learning and development
that enables exceptional people to do their best work.
For more information on D. E. Shaw India, please visit www.deshawindia.com.```

**Comment by Pradhvan** [comment]
Draft
---
We are excited to announce D. E. Shaw India 
(@DEShawGroup) as Platinum Sponsor for PyCon India 2020. 

Read more about D. E. Shaw India in our blog.

Blog Here

#PyConIndia2020

Poster Here


@inovizz good to go ?

**Comment by iamaravindsekar** [comment]
The poster can be found in this url, Thank you :)
[https://drive.google.com/file/d/1nJ4nuZalbPpNtTLCmAsEmiKkXkTlFazE/view?usp=sharing](url)

**Comment by inovizz** [comment]
Few changes -

1. Please replace the text (boilerplate) that appears on clicking our logo under the sponsor's page with the below text instead.

```
Established in 1996 as a technological development center, D. E. Shaw India has become an integral part of the D. E. Shaw group, a global investment and technology development firm. Since its inception, D. E. Shaw India has expanded its business into a broad range of software and financial activities.

Technology is at the core of our business. Our talented and innovative engineers engage in informed problem-solving to process large data sets into useful analytics and forecasts using a combination of technology and deep domain knowledge.

At D. E. Shaw India, our goal is to cultivate an environment of continuous learning and development that enables exceptional people to do their best work.
```

2. Please tag D.E. Shaw India on the LinkedIn post we have done.

3. The Blog PR needs to published (with updated description)

cc @palnabarun @Pradhvan @rayandas
