### ISSUE TITLE
Announce Essentia SoftServ LLP as Silver SPONSOR

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2020-tasks#92]
Scheduled: 24 Sep 9 AM
Sponsor Name: Essentia SoftServ LLP

Sponsor Tier: Silver

Sponsor Website: https://essentiasoftserv.com/
 
Sponsor Description:
Sponsoring PyCon India is a proud moment for us since the conference was pivotal in bringing the Essentia Team together.

To say the least, our founders met at PyCon India 2012, and the community helped us get discovered by prospective clients with a word-of-mouth marketing.

We also have to mention that we have had the chance to hire and mentor some of the most amazing talents from the PyCon community.

This sponsorship is a small token of showing gratitude and support for nurturing and helping a start-up thrive.

Thank you PyCon India.

Sponsor Logo: https://drive.google.com/file/d/1Doq-uVFzW37HFRvbPkBG4V8YvQ19G9wQ/view?usp=sharing

Twitter Handle: essentia_ss

## Tasks
- [x] Social Media announcement @rayandas 
- [x] Blog post announcement @vipulgupta2048 
- [x] Website update to display sponsor logo  @palnabarun 

### Pre 12:00 AM
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @palnabarun
- [x] Deploy the blog and the website @palnabarun 

### At 9:00 AM
- [x] Send the social media announcements out @rayandas

**Comment by Sc0rpi0n101** [comment]
Draft Blog: https://github.com/pythonindia/inpycon-blog/pull/332

**Comment by iamaravindsekar** [comment]
The announcement media can be found in the below url, Thanks :)
[https://drive.google.com/file/d/1K3R5v27eLzK9DGh7SA14UKH-KvdIyhSA/view?usp=sharing](url)

**Comment by Pradhvan** [comment]
Draft
---

We are excited to announce Essentia SoftServ LLP(@essentia_ss) as Silver Sponsor for PyCon India 2020.

Read more about  Essentia SoftServ LLP in our blog.

Blog Link

#PyConIndia2020 

Poster Here

**Comment by Pradhvan** [comment]
Social Media Posts:
---

LinkedIn: https://www.linkedin.com/feed/update/urn:li:activity:6714758095601496064

Twitter: https://twitter.com/pyconindia/status/1308991484583124992

Facebook: https://www.facebook.com/133849919970392/posts/3633091136712902/

**Comment by Pradhvan** [comment]
Thank You everyone for helping in closing the issue.
