### ISSUE TITLE
Announce Sixth Keynote Speaker

### ISSUE THREAD

**Issue by sayanchowdhury** [pythonindia/inpycon2020-tasks#95]
Scheduled for 23 September 2020

## Tasks
- [x] Social Media announcement @Pradhvan 
- [x] Blog post announcement @vipulgupta2048 
- [x] Mailing list announcement  @sayanchowdhury 
- [x] Website update to display the sixth keynote speaker.  @sayanchowdhury @palnabarun 

### Pre 4PM
- [x] Push a low resolution image to server to refer in website and blog @palnabarun @sayanchowdhury 
- [x] Merge the blog post @vipulgupta2048 @Sc0rpi0n101 
- [x] Draft the social media announcement @Pradhvan 
- [x] Merge the website changes @aavrug 

### Post 5PM
- [x] Deploy the blog and the website @palnabarun 
- [x] Send the social media announcements out @Pradhvan 
- [x] Announce on mailing list @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Terri Oda 
Twitter: https://twitter.com/terriko

Terri specializes in saying no and explaining things, which either
describes her professional work as an open source security expert, her
personal time as the parent of a child who always wants to know
“what’s happening?” or her volunteer service bringing new contributors
into Python projects through Google Summer of Code.

**Comment by Sc0rpi0n101** [comment]
Blog: https://github.com/pythonindia/inpycon-blog/pull/334

**Comment by iamaravindsekar** [comment]
Announcement media can be found in the following url, Thanks :)
[https://drive.google.com/file/d/17_yoUuDv3PjudFgSsi23iAqNz-xxyDeU/view?usp=sharing](url)

**Comment by Pradhvan** [comment]
Draft
---

It's our pleasure to announce Terri Oda(@terriko) as the sixth speaker in the keynote lineup of #PyConIndia2020.

Terri is an open-source security expert and helps new contributors contribute to Python projects in @gsoc 

https://in.pycon.org/blog/2020/keynote-announcement-terri-oda.html

Tickets: bit.ly/GetPyConIndiaTickets

Poster Here

**Comment by Pradhvan** [comment]
Social Media Posts
---

Facebook: https://www.facebook.com/133849919970392/posts/3630577916964224/ 

LinkedIn: https://www.linkedin.com/posts/pyconindia_pyconindia2020-python-security-activity-6714499479850033154-iw0_/

Twitter: https://twitter.com/pyconindia/status/1308732596226990082
