### ISSUE TITLE
Create session scripts for Stage sessions on navigator

### ISSUE THREAD

**Issue by raukadah** [pythonindia/inpycon2020-tasks#98]
## Below is the script for handing stage
```
- Day starts
- "Session moderators" take charge of streamyard and ensure that everything is set up
- "Session chat support" take charge of the comment thread of each stage
- "Session lead" ensures the above has been done
- "Session moderators" start stream and check whether things are running fine
- "Session lead" introduces the first speaker (aka Sayan for the address)
- The speaker goes on with their session
- Just before the end of the session, the "session chat support" collates all questions and sends to "session moderators" for showing the questions on the streamyard custom graphics
- The "Session lead" then ends the session by a concluding statement. The "Session lead" may interrupt the questions if they think it is going out of time.
- All this while "Speaker Coordinator" scouts for the next speaker and coordinate with them to ensure their setup is perfectly fine. If on extreme fire, contact WG LEADS ASAP!!!!!!!!!!
```
## TODO

- [ ] Structure the above session
- [ ] Add corner cases
- [ ] Iterate on different session types
